name: Lint

on:
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

concurrency:
  group: "lint"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run build
